import "./globals.css";
import type { Metadata } from "next";
import Header from "./(_components)/Header";

export const metadata: Metadata = {
    title: "무무르",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
